version: '3'
services:
  java:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # Sets Maven repository folder
      - ~/.m2:/root/.m2

      # Sets ssh folder
      #- ~/.ssh:/root/.ssh

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock 

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 

  r-notebook:
    image: "jupyter/r-notebook:d4cbf2f80a2a"
    ports:
      - "8888:8888"
    volumes:
      - "${PWD}:/home/jovyan/work"
    command: start.sh jupyter lab --LabApp.token=''    
